### ISSUE TITLE
New discovery code in solid-logic according to new WebID spec

### ISSUE THREAD

**Issue by timea-solid** [SolidOS/solid-logic#42]
After the discoveryLogic was introduced I noticed we have duplicate function names and duplicate code. 
An overview:
![grafik](https://user-images.githubusercontent.com/4144203/173554340-7d2e014c-eb1d-46f6-ab8a-b0150fb844bb.png)

TODO:

- [x] move functions related to typeIndex from discoveryLogic to typeIndexLogic or decide what is better

- [x] decide which functions should be exposed through SolidLogic object itself.

- [x] propagate refactoring in rest of SolidOS stack.

**Comment by timbl** [comment]
In the new discovery code, we should use the process-wide store rather than having passed to each function. 
So  in fact to have
```
export async function loadPreferences (user: NamedNode)
```
 instead of 
```
export async function loadPreferences (store: LiveStore, user: NamedNode)
```
and so on.  This is large change, but it is a simplifying change, so if we are refactoring let's do it.
